apiVersion: apps/v1
kind: Deployment
metadata:
    name: server-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: server
    template:
        metadata:
            labels:
                component: server
        spec:
            containers:
                -   name: server
                    image: kdocker94/multi-server
                    imagePullPolicy: Always
                    ports:
                        -   containerPort: 5000
                    env:
                        -   name: REDIS_HOST
                            value: redis-cluster-ip-service
                        -   name: REDIS_PORT
                            value: '6379'
                        -   name: PGUSER
                            value: postgres
                        -   name: PGHOST
                            value: postgres-cluster-ip-service
                        -   name: PGPORT
                            value: '5432'
                        -   name: PGDATABASE
                            value: postgres
                        -   name: PGPASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: pgpassword
                                    key: PGPASSWORD
                        -   name: POD_NAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -   name: POD_UUID
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.uid
